# Generated by Django 4.2.16 on 2024-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='character',
            name='path',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.BooleanField(default=True),
        ),
    ]
