# Generated by Django 4.2.16 on 2024-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0002_character_element_character_path_character_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='path',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.BooleanField(),
        ),
    ]
